# Xbox One wired controller
joy_teleop:
  ros__parameters:
    piloting:
      type: topic
      interface_type: "geometry_msgs/msg/Twist"
      topic_name: cmd_vel
      deadman_buttons: []  # Nessun deadman
      axis_mappings:
        linear-x:
          axis: 1  # Stick sinistro su/giù
          scale: -0.4  # invertito
          offset: 0.0
        angular-z:
          axis: 0  # Stick sinistro sinistra/destra
          scale: 2.5
          offset: 0.0

